"""OpenAPI documentation configuration (CRKY-32).

Provides comprehensive API metadata, tag descriptions, and environment-
controlled access to the Swagger UI and ReDoc documentation endpoints.

Access control:
- CK_DOCS_PUBLIC=true (default when CK_AUTH_ENABLED=false): /docs, /redoc, /openapi.json open to all
- CK_DOCS_PUBLIC=false (default when CK_AUTH_ENABLED=true): docs require JWT auth
- Override with CK_DOCS_PUBLIC env var regardless of auth setting
"""

from __future__ import annotations

import os

from .version import VERSION_STRING

# Determine docs access mode
_AUTH_ENABLED = os.environ.get("CK_AUTH_ENABLED", "false").strip().lower() in ("true", "1", "yes")
_DOCS_PUBLIC_OVERRIDE = os.environ.get("CK_DOCS_PUBLIC", "").strip()
if _DOCS_PUBLIC_OVERRIDE:
    DOCS_PUBLIC = _DOCS_PUBLIC_OVERRIDE.lower() in ("true", "1", "yes")
else:
    # Public by default in local mode, protected in production
    DOCS_PUBLIC = not _AUTH_ENABLED

API_VERSION = VERSION_STRING

API_DESCRIPTION = """
# CorridorKey Cloud API

Neural-network-based green screen keyer for professional VFX pipelines.
This API powers the CorridorKey WebUI and provides programmatic access to
clip management, GPU job processing, render farm orchestration, and
organization management.

## Authentication

All API endpoints (except `/api/auth/*` and `/api/health`) require authentication
when `CK_AUTH_ENABLED=true`.

### JWT Bearer Token

Include a Supabase-issued JWT in the `Authorization` header:

```
Authorization: Bearer <your_jwt_token>
```

**Obtaining a token:**

```bash
# Login to get access_token + refresh_token
curl -X POST /api/auth/login \\
  -H "Content-Type: application/json" \\
  -d '{"email": "you@example.com", "password": "your_password"}'

# Response includes access_token (use as Bearer token)
# and refresh_token (use to get new access_token before expiry)
```

**Refreshing tokens:**

```bash
curl -X POST /api/auth/refresh \\
  -H "X-Refresh-Token: <refresh_token>"
```

### Query Parameter Token

For HTML elements that can't set headers (`<img>`, `<video>`), append `?token=<jwt>`:

```
/api/preview/clip_name/input/0?token=eyJhbG...
```

### Node Authentication

Remote worker nodes use per-node tokens generated by org admins:

```
Authorization: Bearer <node_token>
```

Generate tokens via `POST /api/farm/tokens` in the WebUI or API.

## Trust Tiers

Users have a trust tier that controls access:

| Tier | Access Level |
|------|-------------|
| `pending` | Can only check auth status (awaiting admin approval) |
| `member` | Full access to clips, jobs, previews within their org |
| `contributor` | Higher rate limits, same functional access |
| `org_admin` | Can manage org members, nodes, webhooks, IP allowlists |
| `platform_admin` | Full access to everything, admin dashboard |

## Rate Limits

Requests are rate-limited per user (by `user_id`) or per IP (unauthenticated):

| Tier | Requests/min | Job submissions/hr |
|------|-------------|-------------------|
| `pending` | 30 | 0 |
| `member` | 300 | 30 |
| `contributor` | 600 | 60 |
| `org_admin` | 600 | 60 |
| `platform_admin` | Unlimited | Unlimited |
| Unauthenticated | 120 | 10 |

Rate limit headers are included in responses:
- `X-RateLimit-Remaining`: requests remaining in the current window
- `Retry-After`: seconds to wait when limit is exceeded (429 response)

Exempt paths (not rate-limited): health checks, auth status, node agent polling,
VRAM polling, farm listing.

## Webhook Payloads

Webhooks fire on job lifecycle events. Configure per-org via the webhooks API.

### Events

| Event | Trigger |
|-------|---------|
| `job_started` | Job claimed by a worker |
| `job_completed` | Job finished successfully |
| `job_failed` | Job failed with error |
| `node_online` | Worker node came online |
| `node_offline` | Worker node went offline |

### Formats

**JSON** (default):
```json
{
  "event": "job_completed",
  "data": {
    "job_id": "abc123",
    "clip_name": "shot_01",
    "job_type": "inference",
    "frames": 150
  },
  "timestamp": 1710864000.0
}
```

**Discord** (embed format):
```json
{
  "embeds": [{
    "title": "Job Completed",
    "color": 6149241,
    "fields": [
      {"name": "job_id", "value": "abc123", "inline": true},
      {"name": "clip_name", "value": "shot_01", "inline": true}
    ],
    "footer": {"text": "CorridorKey"}
  }]
}
```

**Slack** (blocks format):
```json
{
  "text": "*Job Completed*",
  "blocks": [
    {"type": "header", "text": {"type": "plain_text", "text": "Job Completed"}},
    {"type": "section", "fields": [
      {"type": "mrkdwn", "text": "*job_id:* abc123"},
      {"type": "mrkdwn", "text": "*clip_name:* shot_01"}
    ]}
  ]
}
```

## API Versioning

The current API version is `1.0.0`. The `X-API-Version` response header is included
on all API responses. Future breaking changes will increment the major version.

## Organization Isolation

When auth is enabled, each user's data is scoped to their organization.
Clips, jobs, and storage are isolated per-org. A user can belong to multiple
orgs but interacts with one at a time (their primary/personal org by default).

## Code Examples

### Python (requests)

```python
import requests

BASE = "https://your-server.com"
TOKEN = "your_jwt_token"
HEADERS = {"Authorization": f"Bearer {TOKEN}"}

# List clips
clips = requests.get(f"{BASE}/api/clips", headers=HEADERS).json()

# Submit inference job
resp = requests.post(f"{BASE}/api/jobs/inference", headers=HEADERS, json={
    "clip_names": ["my_clip"],
    "params": {"despill_strength": 0.8}
})
jobs = resp.json()

# Check job status
status = requests.get(f"{BASE}/api/jobs", headers=HEADERS).json()
```

### curl

```bash
# Login
TOKEN=$(curl -s -X POST $BASE/api/auth/login \\
  -H "Content-Type: application/json" \\
  -d '{"email":"you@example.com","password":"pass"}' | jq -r .access_token)

# List clips
curl -H "Authorization: Bearer $TOKEN" $BASE/api/clips

# Submit pipeline job
curl -X POST -H "Authorization: Bearer $TOKEN" \\
  -H "Content-Type: application/json" \\
  -d '{"clip_names":["shot_01"],"alpha_method":"gvm"}' \\
  $BASE/api/jobs/pipeline

# Upload video
curl -X POST -H "Authorization: Bearer $TOKEN" \\
  -F "file=@footage.mp4" "$BASE/api/upload/video?name=my_shot"
```
"""

# Tag metadata for Swagger UI grouping. Order matters — this defines
# the display order in the documentation.
TAG_METADATA = [
    {
        "name": "auth",
        "description": "Authentication — login, signup, invite tokens, token refresh. "
        "These endpoints are public (no JWT required).",
    },
    {
        "name": "clips",
        "description": "Clip management — list, inspect, delete, and move clips within projects. "
        "Requires `member` tier or higher.",
    },
    {
        "name": "jobs",
        "description": "GPU job submission and management — inference, GVM alpha, VideoMaMa, "
        "full pipeline, sharded inference, job cancellation and priority. "
        "Requires `member` tier. Job submissions are rate-limited per tier.",
    },
    {
        "name": "preview",
        "description": "Frame preview, video playback, and download — serves individual frames as PNG, "
        "stitches sequences into MP4 for browser playback, and packages passes as ZIP downloads. "
        "Requires `member` tier.",
    },
    {
        "name": "projects",
        "description": "Project management — create, list, rename, and delete projects. "
        "Projects contain one or more clips. Requires `member` tier.",
    },
    {
        "name": "upload",
        "description": "File upload — video files, image frame sequences (ZIP), alpha hints, "
        "and VideoMaMa masks. Uploads create new projects/clips automatically. "
        "Requires `member` tier. Subject to storage quotas.",
    },
    {
        "name": "system",
        "description": "System information — GPU/CPU stats, VRAM monitoring, model weight management, "
        "local GPU toggle, VRAM limits, and claim delay configuration. "
        "Read endpoints require `member` tier; write endpoints require `platform_admin`.",
    },
    {
        "name": "orgs",
        "description": "Organization management — CRUD for orgs, membership, role assignment, "
        "GPU credits, storage quotas, IP allowlists, and webhooks. "
        "Requires authentication; org-level operations check membership/role.",
    },
    {
        "name": "farm",
        "description": "Render farm management (frontend) — org-scoped node listing, pause/resume, "
        "scheduling, visibility, per-node auth tokens. Members see their org's nodes; "
        "org admins can manage them; platform admins see all.",
    },
    {
        "name": "nodes",
        "description": "Node agent endpoints — registration, heartbeat, job dispatch, file transfer. "
        "Used by remote worker nodes (not the frontend). Authenticated via per-node tokens "
        "or legacy `CK_AUTH_TOKEN`.",
    },
    {
        "name": "admin",
        "description": "Platform administration — user approval/rejection, tier management, "
        "org listing, GPU credit grants, platform statistics, audit log. "
        "Requires `platform_admin` tier.",
    },
    {
        "name": "metrics",
        "description": "Prometheus metrics export at `/metrics`. Enabled via `CK_METRICS_ENABLED=true`. "
        "Includes job queue stats, node health, WebSocket connections, and per-node GPU metrics.",
    },
    {
        "name": "status",
        "description": "Public platform status page — no authentication required. Shows API health, "
        "component statuses, node counts, queue depth, job processing times, and incident history. "
        "Includes a shields.io-compatible SVG badge for README embeds.",
    },
]
